[package]
name = "rust-hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = "0.3"
serde = { version = "1.0", features = ["derive"] }
gethostname = "0.4"
chrono = { version = "0.4", features = ["serde"] }
