apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepseek-interface
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deepseek-interface
  template:
    metadata:
      labels:
        app: deepseek-interface
    spec:
      hostNetwork: true
      containers:
      - name: deepseek-interface
        image: localhost:32000/deepseek-interface:latest
        ports:
        - containerPort: 8080
        env:
        - name: OLLAMA_URL
          value: "http://localhost:11434"
---
apiVersion: v1
kind: Service
metadata:
  name: deepseek-service
spec:
  selector:
    app: deepseek-interface
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deepseek-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
  - host: deepseek.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: deepseek-service
            port:
              number: 80
